apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: si7dyaayr-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-8ce2395338.uc8t.p3.openshiftapps.com/rhtap/rhtap-qe:f7d9433ab0ff2dee0981e193b036db41de1f1e10@sha256:3ff645b4f4024a374e866e822eb83e688c8bb2d500b79bf4154939c9a7729459
          name: container-image
